### PR TITLE
Remove ads

### PR DESCRIPTION
**Pull request by RealPacket**
Why were they even here in the first place?

### CODE REVIEW

**Review by RealPacket — COMMENTED** [review]
Why were they even here in the first place?

**Comment by RealPacket** [comment]
I am deeply sorry that I accidentally removed all your ads from the website, and you have lost a fraction of a cent. I hope you gain that fraction of a cent by getting a job or something else instead of bloating the website with more ads, thank you.

**Comment by RealPacket** [comment]
Blud I haven't even changed anything in the workflows folder 💀

**Comment by RealPacket** [comment]
ads give you a fraction of a cent, I don't think you can cover the monthly server costs with that.

**Comment by Timeraa** [comment]
The ads fully cover our server costs right now and this estimate that Adsense gave you there is not correct at all. I personally don't like showing ads either but people have the option to donate but don't do so.

I would like to merge your PR but since it's our only reliable way to cover the server costs it has to stay.

**Pull request closed without merging**
