### PR TITLE
refactor(contributors): sort users alphabetically

### PR DESCRIPTION
**Pull request by ImRodry**
Title (yes this was tested, yes it works)
Before: 
image
After:
image

### CODE REVIEW

**Comment by TheDropX** [comment]
I think Patrons are sorted by their subscription date already (might be wrong though), so I don't know if this is right to do. I don't feel like this is needed anyways, but I'll leave @Timeraa decide if this will be merged or not.

**Comment by Timeraa** [comment]
> I think Patrons are sorted by their subscription date already (might be wrong though), so I don't know if this is right to do. I don't feel like this is needed anyways, but I'll leave @Timeraa decide if this will be merged or not.

I think the tier would be better but it doesn't really matter imo

**Comment by ImRodry** [comment]
We can have custom sorting per role if you wish but the current order looks overall messy and I feel like an alphabetical order would be much less subjective and would make more sense

**Comment by Timeraa** [comment]
All Patrons only have one role because another one based on the amount is kinda unnecessary imo, so as long as they are sorted into the roles it's fine

**Pull request merged**
